services:
  db-postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: tenpochallenge_db
      POSTGRES_PASSWORD: tenpopass
      POSTGRES_USER: tenpouser
    ports:
      - "5432:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  db-redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"